### ISSUE TITLE
pulsar-flink remove subscription failed ,The client instance is closed

### ISSUE THREAD

**Issue by bin-albin** [streamnative/pulsar-flink#130] opened 2020-09-18 07:02 UTC
**Describe the bug**

flink run in yarn-cluster mode.

An exception occurs after the program has been running for some time.

 2020-09-18 09:58:03,879 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Removing subscription flink-pulsar-3dec829b-e11a-4958-922f-e8ce41e4a823 from topic persistent://2000003485-lctest/monitor-uic/7bd0d02c2aa04cc48718ea86014d70ce
2020-09-18 09:58:03,890 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Successfully removed subscription flink-pulsar-3dec829b-e11a-4958-922f-e8ce41e4a823 from topic persistent://2000003485-lctest/monitor-uic/7bd0d02c2aa04cc48718ea86014d70ce
2020-09-18 09:58:03,890 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Removing subscription flink-pulsar-3dec829b-e11a-4958-922f-e8ce41e4a823 from topic persistent://2000003485-lctest/monitor-uic/42656da6941542c1b8d84f9a37f3a6ba
2020-09-18 09:58:03,899 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Successfully removed subscription flink-pulsar-3dec829b-e11a-4958-922f-e8ce41e4a823 from topic persistent://2000003485-lctest/monitor-uic/42656da6941542c1b8d84f9a37f3a6ba
2020-09-18 09:58:03,915 INFO  org.apache.flink.runtime.taskmanager.Task                     - Source: Custom Source -> Sink: Unnamed (1/1) (73d1f8a89159119536e25ab184ea5a83) switched from RUNNING to FAILED.
java.lang.RuntimeException: Failed to set up cursor for persistent://2000003485-lctest/monitor-uic/7bd0d02c2aa04cc48718ea86014d70ce
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.setupCursor(PulsarMetadataReader.java:234)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.createAndStartReaderThread(PulsarFetcher.java:531)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.runFetchLoop(PulsarFetcher.java:259)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.runWithTopicsDiscovery(FlinkPulsarSource.java:514)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.run(FlinkPulsarSource.java:473)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:196)
Caused by: org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Subscription already exists for topic
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:218)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.createSubscription(TopicsImpl.java:820)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.setupCursor(PulsarMetadataReader.java:230)
	... 7 more
Caused by: org.apache.pulsar.shade.javax.ws.rs.ClientErrorException: HTTP 409 Conflict
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:1122)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1105)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:340)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.createSubscription(TopicsImpl.java:818)
	... 8 more
2020-09-18 09:58:03,916 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Removing subscription flink-pulsar-3dec829b-e11a-4958-922f-e8ce41e4a823 from topic persistent://2000003485-lctest/monitor-uic/7bd0d02c2aa04cc48718ea86014d70ce
2020-09-18 09:58:03,916 ERROR org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource  - Failed to cancel the Pulsar Fetcher java.lang.RuntimeException: Failed to remove cursor for persistent://2000003485-lctest/monitor-uic/7bd0d02c2aa04cc48718ea86014d70ce
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:272)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.cancel(PulsarFetcher.java:418)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:593)
	at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:147)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:136)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:602)
	at org.apache.flink.runtime.taskmanager.Task.cancelInvokable(Task.java:1216)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:775)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:532)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Client instance has been closed.
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyClient.checkNotClosed(JerseyClient.java:327)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.checkNotClosed(JerseyWebTarget.java:140)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.topicPath(TopicsImpl.java:962)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscriptionAsync(TopicsImpl.java:640)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscription(TopicsImpl.java:625)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:265)
	... 9 more

2020-09-18 09:58:03,917 ERROR org.apache.flink.runtime.taskmanager.Task                     - Error while canceling task Source: Custom Source -> Sink: Unnamed (1/1).
java.lang.RuntimeException: java.lang.RuntimeException: Failed to remove cursor for persistent://2000003485-lctest/monitor-uic/7bd0d02c2aa04cc48718ea86014d70ce
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:596)
	at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:147)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:136)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:602)
	at org.apache.flink.runtime.taskmanager.Task.cancelInvokable(Task.java:1216)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:775)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:532)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to remove cursor for persistent://2000003485-lctest/monitor-uic/7bd0d02c2aa04cc48718ea86014d70ce
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:272)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.cancel(PulsarFetcher.java:418)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:593)
	... 7 more
Caused by: java.lang.IllegalStateException: Client instance has been closed.
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyClient.checkNotClosed(JerseyClient.java:327)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.checkNotClosed(JerseyWebTarget.java:140)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.topicPath(TopicsImpl.java:962)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscriptionAsync(TopicsImpl.java:640)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscription(TopicsImpl.java:625)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:265)

[pulsar-flink.log](https://github.com/streamnative/pulsar-flink/files/5243910/pulsar-flink.log)

**Comment by bin-albin** [comment] 2020-09-18 07:03
fink 1.10 and pulsar 2.6.0

**Comment by jianyun8023** [comment] 2020-09-18 17:02
I know this problem, it is caused by wrongly closing `pulsarMateReader`. We will fix this issue as soon as possible.

**Comment by bin-albin** [comment] 2020-09-21 16:16
yes,indeed , I have identified the problem and am working on it

**Comment by roee-hershko** [comment] 2020-11-14 16:37
is it fixed yet?
one more might related issue - every time flink job fails i am forced to restart all the task managers to make it work again
getting "java.lang.OutOfMemoryError: Direct buffer memory"

**Comment by jianyun8023** [comment] 2020-12-04 13:11
moved #203

**Closed by jianyun8023** 2020-12-04 13:11 UTC
Labels: type/bug, workflow::in-progress
