### ISSUE TITLE
[BUG] Topic is created with Flink Pulsar Source [with Non-existing Topic] when Auto Topic creation is disable in KoP broker.conf

### ISSUE THREAD

**Issue by devprashantksinha** [streamnative/pulsar-flink#62] opened 2020-03-27 08:26 UTC
**Describe the bug**
When Auto topic creation is disabled in KoP, non partitioned topic is getting created with Flink Pulsar Source.

**To Reproduce**
1. Disable auto topic creation in KoP using broker.conf
2. Try to create a consumer using Flink Pulsar Source with non existing topic
3. Do a topics list using pulsar admin to see a non partitioned topic is created  

**Expected behavior**
Topics should not be created while creating FlinkPulsarSource[ FlinkPulsarConsumer] when auto topic creation is turned off in KoP.

_Please let us know the behavior of Flink Pulsar Sink and Source in the absence of topics. Should it fail ?_

**Additional context**
Disabling of auto topic creation is although honored by FlinkPulsarSink and a clear exception is observed in KoP logs. Please find more details below and attached logs[refer kop-2].( 
[kop-1.log](https://github.com/streamnative/pulsar-flink/files/4392224/kop-1.log)
[kop-2.log](https://github.com/streamnative/pulsar-flink/files/4392225/kop-2.log)
[kop-0.log](https://github.com/streamnative/pulsar-flink/files/4392226/kop-0.log)
)

**Exception Details**
-------------------------------------------------------------------------------------------------------
Source Topic : dp_moving_average_source_data_topic6 [ Getting created . Not expected ]
Sink Topics :  dp_moving_average_dest_data_topic6 [Not getting created . Expected ]

### Expected an exception but topic is getting created: 
```
06:33:20.672 [pulsar-web-31-3] INFO  org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [itomdipulsar-proxy][persistent://public/default/**dp_moving_average_source_data_topic6**] Creating subscription flink-pulsar-60659686-c796-4dec-b9b7-0dc7e85a28d9 at message id 9223372036854775807:9223372036854775807:-1
06:33:20.677 [pulsar-ordered-OrderedExecutor-1-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Opening managed ledger public/default/persistent/dp_moving_average_source_data_topic6
06:33:20.679 [bookkeeper-ml-workers-OrderedExecutor-4-0] INFO  org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper - **Creating '/managed-ledgers/public/default/persistent/dp_moving_average_source_data_topic6'**
06:33:20.686 [pulsar-ordered-OrderedExecutor-2-0-EventThread] INFO  org.apache.pulsar.zookeeper.ZooKeeperChildrenCache - [State:CONNECTED Timeout:30000 sessionid:0x3005fc2eacc0006 local:/172.16.16.160:60330 remoteserver:itomdipulsar-zookeeper-2.itomdipulsar-zookeeper/172.16.16.169:2181 lastZxid:4295022680 xid:16226 sent:16226 recv:16406 queuedpkts:0 pendingresp:0 queuedevents:1] Received ZooKeeper watch event: WatchedEvent state:SyncConnected type:NodeChildrenChanged path:/managed-ledgers/public/default/persistent
06:33:20.688 [pulsar-ordered-OrderedExecutor-2-0-EventThread] INFO  org.apache.pulsar.zookeeper.ZooKeeperChildrenCache - reloadCache called in zookeeperChildrenCache for path /managed-ledgers/public/default/persistent
06:33:20.692 [bookkeeper-ml-workers-OrderedExecutor-4-0] WARN  org.apache.bookkeeper.client.BookieWatcherImpl - New ensemble: [itomdipulsar-bookkeeper-1.itomdipulsar-bookkeeper.pulsar-loader.svc.cluster.local.:3181, itomdipulsar-bookkeeper-2.itomdipulsar-bookkeeper.pulsar-loader.svc.cluster.local.:3181] is not adhering to Placement Policy. quarantinedBookies: []
```

### Exception as expected in case of Flink Pulsar Sink : 
```
06:33:20.576 [bookkeeper-ml-workers-OrderedExecutor-3-0] ERROR org.apache.pulsar.broker.service.ServerCnx - [/172.16.16.1:39496] **Failed to create topic persistent://public/default/dp_moving_average_dest_data_topic6**
java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_242]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_242]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618) ~[?:1.8.0_242]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_242]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_242]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_242]
        at org.apache.pulsar.broker.service.BrokerService$2.openLedgerFailed(BrokerService.java:926) ~[org.apache.pulsar-pulsar-broker-2.5.0-ad0224407.jar:2.5.0-ad0224407]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.lambda$asyncOpen$8(ManagedLedgerFactoryImpl.java:343) ~[org.apache.pulsar-managed-ledger-2.5.0-ad0224407.jar:2.5.0-ad0224407]
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:884) ~[?:1.8.0_242]
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:866) ~[?:1.8.0_242]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_242]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_242]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl$2.initializeFailed(ManagedLedgerFactoryImpl.java:336) ~[org.apache.pulsar-managed-ledger-2.5.0-ad0224407.jar:2.5.0-ad0224407]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl$1.operationFailed(ManagedLedgerImpl.java:338) ~[org.apache.pulsar-managed-ledger-2.5.0-ad0224407.jar:2.5.0-ad0224407]
        at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper.lambda$null$1(MetaStoreImplZookeeper.java:164) ~[org.apache.pulsar-managed-ledger-2.5.0-ad0224407.jar:2.5.0-ad0224407]
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [org.apache.pulsar-managed-ledger-2.5.0-ad0224407.jar:2.5.0-ad0224407]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_242]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_242]
        ... 18 more
```

**Comment by jiazhai** [comment] 2020-04-07 00:18
looks like there is operation to create partitioned topic:
```
08:12:23.541 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  org.apache.pulsar.broker.admin.AdminResource - [null] Successfully created partitions for topic persistent://public/default/topic-5
08:12:23.542 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/Apr/2020:08:12:23 +0800] "PUT /admin/v2/persistent/public/default/topic-5/partitions HTTP/1.1" 204 0 "-" "Pulsar-Java-v2.4.2" 18
08:12:23.542 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  org.apache.pulsar.zookeeper.ZooKeeperChildrenCache - reloadCache called in zookeeperChildrenCache for path /managed-ledgers/public/default/persistent
08:12:23.825 [ForkJoinPool.commonPool-worker-6] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/Apr/2020:08:12:23 +0800] "GET /admin/v2/schemas/public/default/topic-5/schema HTTP/1.1" 404 0 "-" "Pulsar-Java-v2.4.2" 221
08:12:24.047 [pulsar-web-43-12] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/Apr/2020:08:12:24 +0800] "GET /admin/v2/persistent/public/default/topic-5/partitions HTTP/1.1" 200 16 "-" "Pulsar-Java-v2.4.2" 2
08:12:24.047 [pulsar-web-43-14] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/Apr/2020:08:12:24 +0800] "GET /admin/v2/persistent/public/default/topic-5/partitions HTTP/1.1" 200 16 "-" "Pulsar-Java-v2.4.2" 2
08:12:24.059 [pulsar-web-43-15] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/Apr/2020:08:12:24 +0800] "GET /admin/v2/persistent/public/default/topic-5/partitions HTTP/1.1" 200 16 "-" "Pulsar-Java-v2.4.2" 3
08:12:24.118 [pulsar-web-43-15] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/Apr/2020:08:12:24 +0800] "GET /admin/v2/persistent/public/default/topic-5/partitions HTTP/1.1" 200 16 "-" "Pulsar-Java-v2.4.2" 3
08:12:24.118 [pulsar-web-43-12] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/Apr/2020:08:12:24 +0800] "GET /admin/v2/persistent/public/default/topic-5/partitions HTTP/1.1" 200 16 "-" "Pulsar-Java-v2.4.2" 3
08:12:24.118 [pulsar-web-43-3] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/Apr/2020:08:12:24 +0800] "GET /admin/v2/persistent/public/default/topic-5/partitions HTTP/1.1" 200 16 "-" "Pulsar-Java-v2.4.2" 2
08:12:24.127 [pulsar-web-43-2] INFO  org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [null][persistent://public/default/topic-5-partition-0] Creating subscription flink-pulsar-7ac9aac7-764b-48cc-b959-c6e41e39dc07 at message id -1:-1:-1
08:12:24.127 [pulsar-web-43-6] INFO  org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [null][persistent://public/default/topic-5-partition-2] Creating subscription flink-pulsar-7ac9aac7-764b-48cc-b959-c6e41e39dc07 at message id -1:-1:-1
08:12:24.127 [pulsar-web-43-23] INFO  org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [null][persistent://public/default/topic-5-partition-1] Creating subscription flink-pulsar-7ac9aac7-764b-48cc-b959-c6e41e39dc07 at message id -1:-1:-1
08:12:24.128 [pulsar-ordered-OrderedExecutor-6-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Opening managed ledger public/default/persistent/topic-5-partition-0
08:12:24.128 [pulsar-ordered-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Opening managed ledger public/default/persistent/topic-5-partition-2
08:12:24.128 [pulsar-ordered-OrderedExecutor-7-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Opening managed ledger public/default/persistent/topic-5-partition-1
```

**Comment by jiazhai** [comment] 2020-04-07 03:44
Synced with @yjshen . This admin command is used in pulsar flink, but not affected by the topic-auto-create setting: 
```
 admin.topics().createSubscription("topic-name", "sub-name", MessageId.latest);
```
This is more of a Pulsar side issue. @yjshen will help provide a fix for this.

**Comment by jiazhai** [comment] 2020-04-07 03:50
At lease, this method `internalCreateSubscription` need fix to check the autocreate setting.
![image](https://user-images.githubusercontent.com/6348208/78628159-fc990a80-78c5-11ea-82e5-0f81f49edb1c.png)

**Comment by devprashantksinha** [comment] 2020-04-07 05:28
@jiazhai : Great you are able to reproduce it.

**Comment by jiazhai** [comment] 2020-04-07 11:19
@devprashantksinha Yes, it could be reproduced, and there are 2 caller in  class `PulsarMetadataReader`.
```
                admin.topics().createSubscription(entry.getKey(), subscriptionName, entry.getValue());
                admin.topics().createSubscription(topic, subscriptionName, defaultPosition);
```

PR https://github.com/apache/pulsar/pull/6685 is for the fix.

**Comment by sijie** [comment] 2020-04-09 22:21
#6685 is merged. So close this issue.

**Closed by sijie** 2020-04-09 22:21 UTC
Labels: type/bug
