### ISSUE TITLE
[FEATURE] Support reading from compacted topic

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-flink#88] opened 2020-06-01 06:56 UTC
*Motivation*

Currently, the Flink connector doesn't support reading from compacted topic. We need to support this feature.

**Comment by Huanli-Meng** [comment] 2020-06-01 12:46
I think the doc should be updated if the issue is fixed. right? @sijie

**Comment by sijie** [comment] 2020-06-01 23:32
I think the feature is already there. We need to update the documentation.

**Comment by Huanli-Meng** [comment] 2020-06-19 00:32
@sijie , any background info about this feature? Thanks.

**Comment by Huanli-Meng** [comment] 2020-07-03 01:07
@sijie , any PR about this feature to facilitate tracking the background information? Thanks

**Comment by reswqa** [comment] 2020-11-27 09:13
move this feature to #184 and close this issue because that issue have more detail context.

**Closed by reswqa** 2020-11-27 09:13 UTC
Labels: area/Pulsar-doc, triage/week-23, type/feature, workflow::todo
