### ISSUE TITLE
[BUG] Exception: Client instance has been closed.

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#203] opened 2020-12-04 13:08 UTC
**Describe the bug**

We often encounter `Exception: Client instance has been closed.
We have solved the problem that the client instance has been closed due to a small cachedPulsarClient, but this does not solve the problem.

This error is also found in our unit tests, but it does not affect the normal execution of the tests.

Now the speculated causes are
1. in the concurrent case, one thread closes the used client, causing an error in the other thread.
2. the Broker Service actively closes the connection.

Now you need to verify and fix this issue.

```
[org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:610)]: Failed to cancel the Pulsar Fetcher java.lang.RuntimeException:Failed to remove cursor for persistent://dev/dbtest/flink-partition-0
at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:272)
at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.cancel(PulsarFetcher.java:419)
at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:608)
at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:134)
at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:157)
at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:508)
at org.apache.flink.runtime.taskmanager.Task.cancelInvokable(Task.java:1281)
at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:773)
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Client instance has been closed.
at org.apache.pulsar.shade.org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169)
at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyClient.checkNotClosed(JerseyClient.java:327)
at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.checkNotClosed(JerseyWebTarget.java:140)
at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151)
at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
at org.apache.pulsar.client.admin.internal.TopicsImpl.topicPath(TopicsImpl.java:962)
at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscriptionAsync(TopicsImpl.java:640)
at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscription(TopicsImpl.java:625)
at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:265)
... 9 more

2020-06-24 17:48:28 ERROR Task [org.apache.flink.runtime.taskmanager.Task.cancelInvokable(Task.java:1284)]: Error while canceling task Source: Custom Source -> Sink: Print to Std. Out (1/1).
java.lang.RuntimeException: java.lang.RuntimeException: Failed to remove cursor for persistent://dev/dbtest/flink-partition-0
at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:611)
at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:134)
at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:157)
at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:508)
at org.apache.flink.runtime.taskmanager.Task.cancelInvokable(Task.java:1281)
at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:773)
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to remove cursor for persistent://dev/dbtest/flink-partition-0
at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:272)
at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.cancel(PulsarFetcher.java:419)
at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:608)
... 7 more
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bicouy0** [comment] 2020-12-11 15:00
Having the same problem when trying to connect a pulsar source to a pulsar sink : the sink fail to create a producer.

15:57:01.626 [Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (6/8)] INFO  o.a.f.s.c.pulsar.internal.CachedPulsarClient - Closing the Pulsar client with conifg ClientConfigurationData(serviceUrl=pulsar://localhost:6650, serviceUrlProvider=null, authentication=org.apache.pulsar.client.impl.auth.AuthenticationDisabled@705f5ea0, authPluginClassName=null, authParams=null, authParamMap=null, operationTimeoutMs=30000, statsIntervalSeconds=60, numIoThreads=1, numListenerThreads=1, connectionsPerBroker=1, useTcpNoDelay=true, useTls=false, tlsTrustCertsFilePath=, tlsAllowInsecureConnection=false, tlsHostnameVerificationEnable=false, concurrentLookupRequest=5000, maxLookupRequest=50000, maxLookupRedirects=20, maxNumberOfRejectedRequestPerConnection=50, keepAliveIntervalSeconds=30, connectionTimeoutMs=10000, requestTimeoutMs=60000, initialBackoffIntervalNanos=100000000, maxBackoffIntervalNanos=60000000000, listenerName=null, useKeyStoreTls=false, sslProvider=null, tlsTrustStoreType=JKS, tlsTrustStorePath=null, tlsTrustStorePassword=null, tlsCiphers=[], tlsProtocols=[], proxyServiceUrl=null, proxyProtocol=null, clock=SystemClock[Europe/Paris])
15:57:01.626 [Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (3/8)] INFO  o.a.f.s.c.pulsar.internal.CachedPulsarClient - Closing the Pulsar client with conifg ClientConfigurationData(serviceUrl=pulsar://localhost:6650, serviceUrlProvider=null, authentication=org.apache.pulsar.client.impl.auth.AuthenticationDisabled@1d555388, authPluginClassName=null, authParams=null, authParamMap=null, operationTimeoutMs=30000, statsIntervalSeconds=60, numIoThreads=1, numListenerThreads=1, connectionsPerBroker=1, useTcpNoDelay=true, useTls=false, tlsTrustCertsFilePath=, tlsAllowInsecureConnection=false, tlsHostnameVerificationEnable=false, concurrentLookupRequest=5000, maxLookupRequest=50000, maxLookupRedirects=20, maxNumberOfRejectedRequestPerConnection=50, keepAliveIntervalSeconds=30, connectionTimeoutMs=10000, requestTimeoutMs=60000, initialBackoffIntervalNanos=100000000, maxBackoffIntervalNanos=60000000000, listenerName=null, useKeyStoreTls=false, sslProvider=null, tlsTrustStoreType=JKS, tlsTrustStorePath=null, tlsTrustStorePassword=null, tlsCiphers=[], tlsProtocols=[], proxyServiceUrl=null, proxyProtocol=null, clock=SystemClock[Europe/Paris])
15:57:01.626 [Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (2/8)] INFO  o.a.f.s.c.pulsar.internal.CachedPulsarClient - Closing the Pulsar client with conifg ClientConfigurationData(serviceUrl=pulsar://localhost:6650, serviceUrlProvider=null, authentication=org.apache.pulsar.client.impl.auth.AuthenticationDisabled@1e7a5d97, authPluginClassName=null, authParams=null, authParamMap=null, operationTimeoutMs=30000, statsIntervalSeconds=60, numIoThreads=1, numListenerThreads=1, connectionsPerBroker=1, useTcpNoDelay=true, useTls=false, tlsTrustCertsFilePath=, tlsAllowInsecureConnection=false, tlsHostnameVerificationEnable=false, concurrentLookupRequest=5000, maxLookupRequest=50000, maxLookupRedirects=20, maxNumberOfRejectedRequestPerConnection=50, keepAliveIntervalSeconds=30, connectionTimeoutMs=10000, requestTimeoutMs=60000, initialBackoffIntervalNanos=100000000, maxBackoffIntervalNanos=60000000000, listenerName=null, useKeyStoreTls=false, sslProvider=null, tlsTrustStoreType=JKS, tlsTrustStorePath=null, tlsTrustStorePassword=null, tlsCiphers=[], tlsProtocols=[], proxyServiceUrl=null, proxyProtocol=null, clock=SystemClock[Europe/Paris])
15:57:01.626 [Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (6/8)] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://localhost:6650
15:57:01.626 [Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (3/8)] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://localhost:6650
15:57:01.626 [Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (2/8)] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://localhost:6650
15:57:01.681 [Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (5/8)] ERROR o.a.f.s.connectors.pulsar.FlinkPulsarSinkBase - Failed to create producer for topic public/default/out
15:57:01.681 [Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (1/8)] ERROR o.a.f.s.connectors.pulsar.FlinkPulsarSinkBase - Failed to create producer for topic public/default/out
15:57:01.683 [Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (7/8)] ERROR o.a.f.s.connectors.pulsar.FlinkPulsarSinkBase - Failed to create producer for topic public/default/out
15:57:01.695 [Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (7/8)] WARN  org.apache.flink.runtime.taskmanager.Task - Source: Custom Source -> (Sink: Print to Std. Out, Sink: Unnamed) (7/8) (9eb3a131708ce6d42081d00fdca075c2) switched from RUNNING to FAILED.
java.lang.RuntimeException: org.apache.pulsar.client.api.PulsarClientException$AlreadyClosedException: Client already closed : state = Closed
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSinkBase.createProducer(FlinkPulsarSinkBase.java:268)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSinkBase.open(FlinkPulsarSinkBase.java:188)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSink.open(FlinkPulsarSink.java:34)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:291)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$0(StreamTask.java:479)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:92)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:475)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:528)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.pulsar.client.api.PulsarClientException$AlreadyClosedException: Client already closed : state = Closed
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:870)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:93)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSinkBase.createProducer(FlinkPulsarSinkBase.java:265)
	... 13 common frames omitted

**Comment by bicouy0** [comment] 2020-12-11 15:05
Scala program to reproduce (flink 1.11.2, scala 2.12.12, pulsar 2.6.2)

```scala
import org.apache.flink.api.common.serialization.SimpleStringSchema
import org.apache.flink.api.java.utils.ParameterTool
import org.apache.flink.streaming.api.scala._
import org.apache.flink.streaming.connectors.pulsar._
import org.apache.flink.streaming.connectors.pulsar.internal._
import org.apache.flink.table.api.DataTypes

import java.util.{Optional, Properties}

object SimpleCopy {

  val stringSchema = new SimpleStringSchema

  def main(args: Array[String]): Unit = {
    val params: ParameterTool = ParameterTool.fromArgs(args)
    val serviceUrl = params.get("service-url", "pulsar://localhost:6650")
    val adminUrl = params.get("admin-url", "http://localhost:8080")

    val env = StreamExecutionEnvironment.getExecutionEnvironment

    val sourceDeserializer = new PulsarDeserializationSchemaWrapper(stringSchema)

    val sourceProperties = new Properties()
    sourceProperties.setProperty("topic", "public/default/in")

    val source = new FlinkPulsarSource(
      serviceUrl,
      adminUrl,
      sourceDeserializer,
      sourceProperties
    )
    source.setStartFromEarliest()

    val strings = env.addSource(source)

    strings.print()

    val sinkSerializer = new PulsarSerializationSchemaWrapper.Builder(stringSchema)
      .useAtomicMode(DataTypes.STRING())
      .build()

    val sinkProperties = new Properties()
    val sink = new FlinkPulsarSink(
      serviceUrl,
      adminUrl,
      Optional.of("public/default/out"),
      sinkProperties,
      sinkSerializer
    )

    strings.addSink(sink)

    env.execute("simple-copy")
  }

}

```

**Comment by reswqa** [comment] 2020-12-11 15:57
@bicouy0 
Thank you very much for your feedback. There are a few questions to confirm.
1. Is this problem recurring every time you run it?
2, see your code logic , topic "public/default/in" seems already exist data, this topic of the data's schema whether the Schema.String?
3、What is the version of pulsar-flink-connector that you used?
4、Can you provide the complete log file if it is convenient?
Thanks again!

**Comment by bicouy0** [comment] 2020-12-11 17:25
> 1. Is this problem recurring every time you run it?

Yes, at each run.

> 2. see your code logic , topic "public/default/in" seems already exist data, Is the schema of these data in pulsar is Schema.String?

Yes it's a simple string schema topic.

> 3. What is the version of pulsar-flink-connector that you used?

I'm using "io.streamnative.connectors" % "pulsar-flink-connector-2.12-1.11" % "2.5.6.1", and also tried "2.5.8-SNAPSHOT"

> 4. Can you provide the complete log file if it is convenient?

https://gist.github.com/bicouy0/0e24044f31eda48a971dced4a0f798eb

> 
> Thanks again!

**Comment by reswqa** [comment] 2020-12-12 11:50
@bicouy0 
I tested it and the problem should be caused by a bug within pulsar, which will eventually cause our cache for pularClient to be cleaned, resulting in the close of the client. 
Before we re-release the next version, you can increase the CLIENT_CACHE_SIZE_OPTION_KEY value to the sink configuration like code blow, which will make the pool size of the guava cache larger. The key point is not allowing the parallelism of the sink operator to be greater than that value, while the default parallelism of flink is 5 and the default value of that configuration is also 5, which eventually leads to the bug you encountered.
We will fix this problem in the next release, and then you won't need to adjust this configuration item.

```
        Properties sinkProperties = new Properties();
        sinkProperties.setProperty(PulsarOptions.CLIENT_CACHE_SIZE_OPTION_KEY, "100");
        FlinkPulsarSink<String> sink = new FlinkPulsarSink<String>(
                serviceUrl,
                adminUrl,
                Optional.of("public/default/out"),
                sinkProperties,
                sinkSerializer
        );
```

**Comment by bicouy0** [comment] 2020-12-12 12:43
I confirm the property fixed the problem

**Closed** 2021-01-25 01:04 UTC
Labels: type/bug

**Comment by jianyun8023** [comment] 2021-01-25 01:08
Now there is one more case to deal with, when the service is actively shut down, whether it is a reconnection or a task failure.
I will open a new issue to handle this situation. #246
