### ISSUE TITLE
[BUG] java.lang.RuntimeException: start message id beyond the last commit

### ISSUE THREAD

**Issue by ericshao** [streamnative/pulsar-flink#454] opened 2021-11-04 13:08 UTC
**Describe the bug**
java.lang.RuntimeException: start message id beyond the last commit
	at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.handleTooLargeCursor(ReaderThread.java:159)
	at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.run(ReaderThread.java:103)

**To Reproduce**
Flink 1.13.2
Pulsar 2.8.1
pulsar-flink-connector 1.13.1.4

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by syhily** [comment] 2021-11-04 15:25
This situation normally happens when the start position (start message id) in Flink state is a latter message compared to the committed message id (a message id acknowledged by the connector).

Can you confirm that this exception only happens when the application restarts from a checkpoint? Or can you give me a procession on how to reproduce this exception?

BYW, can you check the log to see if there is some cursor commit error message.

If you are sure that the state (start message id) is correct. You can disable fall on data loss option `PulsarOptions.FAIL_ON_DATA_LOSS_OPTION_KEY`

**Comment by syhily** [comment] 2021-11-05 07:46
Hi @ericshao can you confirm the situation that I commented above?

**Comment by ericshao** [comment] 2021-11-05 10:34
Not only happens restart from checkpoint, just after an uncertain time of perfect streaming it happens

No cursor commit error message found in log

**Comment by syhily** [comment] 2021-11-07 12:10
I can't reproduce this error on my local machine. Can you show me a clear process on how to reproduce this?

**Comment by ericshao** [comment] 2021-11-08 16:00
Couldn't definitely reproduce this exception either.I doubt it may be resulted by checkpoint failure.

Next time it happened I'll post more detailed logs

**Comment by syhily** [comment] 2021-11-10 07:55
@ericshao OK, I'll temporarily close this issue. You can PING me anytime you see it again.

**Closed by syhily** 2021-11-10 07:55 UTC
Labels: type/bug, platform/data-processing
